#!/usr/bin/env bash
# ──────────────────────────────────────────────
# scripts/export_agent_env.sh
# Synchronizes Infrastructure Contract & Virtual Keys into kruemel-ai-agents
# ──────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"
AGENTS_DIR="$(cd "${ROOT_DIR}/.." && pwd)/kruemel-ai-agents"

source "${ROOT_DIR}/.env"

echo "🔍 Reading Virtual Keys from LiteLLM Database..."

PARSED_KEYS=$(python3 - <<EOF
import urllib.request, json, os

master_key = "${LITELLM_MASTER_KEY}"
base_url = "http://localhost:4000"

req = urllib.request.Request(f"{base_url}/key/list", headers={"Authorization": f"Bearer {master_key}"})
key_map = {}
try:
    with urllib.request.urlopen(req, timeout=10) as r:
        data = json.loads(r.read().decode())
        for k in data.get("keys", []):
            try:
                info_req = urllib.request.Request(f"{base_url}/key/info?key={k}", headers={"Authorization": f"Bearer {master_key}"})
                with urllib.request.urlopen(info_req, timeout=5) as ir:
                    info = json.loads(ir.read().decode()).get("info", {})
                    alias = info.get("key_alias")
                    if alias:
                        key_map[alias] = k
            except Exception:
                pass
except Exception as e:
    pass

print(json.dumps(key_map))
EOF
)

KEY_PO=$(python3 -c "import json; print(json.loads('''$PARSED_KEYS''').get('kruemel-agent-po', ''))")
KEY_ARCHITECT=$(python3 -c "import json; print(json.loads('''$PARSED_KEYS''').get('kruemel-agent-architect', ''))")
KEY_CODER=$(python3 -c "import json; print(json.loads('''$PARSED_KEYS''').get('kruemel-agent-coder', ''))")
KEY_RESEARCHER=$(python3 -c "import json; print(json.loads('''$PARSED_KEYS''').get('kruemel-agent-researcher', ''))")
KEY_DEVOPS=$(python3 -c "import json; print(json.loads('''$PARSED_KEYS''').get('kruemel-agent-devops', ''))")

CONTRACT_JSON="${ROOT_DIR}/config/infra_contract.json"
cat > "$CONTRACT_JSON" <<EOF
{
  "version": "1.0.0",
  "gateway": {
    "url": "http://localhost:4000",
    "master_key": "${LITELLM_MASTER_KEY}"
  },
  "roles": {
    "agent-po": {
      "model": "local-general",
      "key_alias": "kruemel-agent-po",
      "token": "${KEY_PO}",
      "tools": ["spec_mcp", "qdrant_mcp", "memgraph_mcp"]
    },
    "agent-architect": {
      "model": "local-general",
      "key_alias": "kruemel-agent-architect",
      "token": "${KEY_ARCHITECT}",
      "tools": ["architecture_mcp", "spec_mcp", "qdrant_mcp", "memgraph_mcp"]
    },
    "agent-coder": {
      "model": "local-coder",
      "key_alias": "kruemel-agent-coder",
      "token": "${KEY_CODER}",
      "tools": ["filesystem_mcp", "sandbox_mcp", "github_mcp", "qdrant_mcp"]
    },
    "agent-researcher": {
      "model": "local-general",
      "key_alias": "kruemel-agent-researcher",
      "token": "${KEY_RESEARCHER}",
      "tools": ["searxng_mcp", "browserless_mcp", "qdrant_mcp"]
    },
    "agent-devops": {
      "model": "local-general",
      "key_alias": "kruemel-agent-devops",
      "token": "${KEY_DEVOPS}",
      "tools": ["docker_mcp", "litellm_mcp", "cloudflare_mcp", "fritzbox_mcp", "qdrant_mcp", "memgraph_mcp"]
    }
  },
  "endpoints": {
    "searxng": "http://localhost:1514",
    "memgraph_bolt": "bolt://localhost:7687",
    "memgraph_lab": "http://localhost:1515",
    "browserless": "http://localhost:1516",
    "sandbox": "http://localhost:1517",
    "qdrant": "http://localhost:6333",
    "langfuse": "http://localhost:3000",
    "hub": "http://localhost:1512",
    "agent_gateway": "http://localhost:1518"
  }
}
EOF
echo "✓ Generated ${CONTRACT_JSON}"

if [ -d "$AGENTS_DIR" ]; then
  TARGET_ENV="${AGENTS_DIR}/.env"
  cat > "$TARGET_ENV" <<EOF
# ──────────────────────────────────────────────
# Auto-generated by kruemel-ai-infra (make sync-agents)
# DO NOT EDIT DIRECTLY – run 'make sync-agents' in infra to regenerate
# ──────────────────────────────────────────────

# Gateway & LiteLLM
OPENAI_BASE_URL=http://localhost:4000/v1
LITELLM_API_BASE=http://localhost:4000
LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}
AGENT_GATEWAY_URL=http://localhost:1518

# Role-specific Virtual Keys (Strict Isolation)
PO_API_KEY=${KEY_PO}
ARCHITECT_API_KEY=${KEY_ARCHITECT}
CODER_API_KEY=${KEY_CODER}
RESEARCHER_API_KEY=${KEY_RESEARCHER}
DEVOPS_API_KEY=${KEY_DEVOPS}

# Standard Model Aliases (Routed to Local Ollama)
MODEL_GENERAL=local-general
MODEL_CODER=local-coder
MODEL_EMBEDDING=nomic-embed-text

# Standalone Endpoints (if called directly)
SEARXNG_URL=http://localhost:1514
MEMGRAPH_BOLT_URL=bolt://localhost:7687
QDRANT_URL=http://localhost:6333
SANDBOX_URL=http://localhost:1517
BROWSERLESS_URL=http://localhost:1516
LANGFUSE_HOST=http://localhost:3000
EOF
  echo "✨ Synchronized agent environment -> ${TARGET_ENV}"
else
  echo "Notice: Directory '${AGENTS_DIR}' not found. Contract saved to config/infra_contract.json."
fi
